export const INIT_STATE = 'INIT_STATE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_VIDEOS = 'SET_VIDEOS';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
